# Построение доверительных интервалов

In [154]:
import numpy as np
import scipy.stats as st
import math

In [155]:
n = 100
gamma=0.95
p = 0.43
xg= st.norm.ppf((1 + gamma) / 2)

## По центральной предельной теореме

In [156]:
x = np.random.binomial(1, p, n)
th = x.mean()
a1 = max(th - xg*(th*(1 - th)/n) ** 0.5, 0)
a2 = min(th + xg*(th*(1 - th)/n) ** 0.5, 1)
print(a1)
print(a2)

0.2659217287420774
0.45407827125792255


## Дельта метод

In [157]:
b1 = (math.sin(math.asin(th**0.5) - xg /2 /n**0.5))**2
b2 = (math.sin(math.asin(th**0.5) + xg /2 /n**0.5))**2
print(b1)
print(b2)

0.2692033266150449
0.4561575214904965


## Простой бутстраппинг

In [158]:
n = 100
M = 1000
Y = np.random.binomial(1, th, (M, n))
v = Y.mean(axis = 1)
z = v - th
q = np.percentile(z, [(1-gamma)*50, (1 + gamma)*50])
q+=th
q

array([0.27, 0.46])

In [159]:
t = np.percentile(v, [(1-gamma)*50, (1 + gamma)*50])
t

array([0.27, 0.46])

## Студентизированный бутстраппинг 

In [161]:
s = (th*(1 - th/n))**0.5 #сигма тета
Y1 = np.random.binomial(1, th, (M, n))
V = Y1.mean(axis = 1)
ss = (V*(1 - V / n)) ** 0.5 #сигма по каждой строчке матрицы
z = (V - th) / ss
t = np.percentile(z, [(1-gamma)*50, (1 + gamma)*50])
t = np.array( [t[1] * (-s), t[0] * (-s)])
t += th
t

array([0.2714904 , 0.46387615])