# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
np.show_config()

1.14.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


#### 4.  How to find the memory size of any array (★☆☆)

In [23]:
print("%d bytes" % (a.size * a.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [24]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
a = np.zeros(10)
a[4] = 1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [33]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [37]:
a = np.arange(0, 9)
a.reshape(3,3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [40]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [46]:
type(np.eye(3))

numpy.ndarray

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [48]:
np.random.rand(3, 3, 3)

array([[[0.43532459, 0.77150642, 0.82593121],
        [0.863583  , 0.83104267, 0.49635084],
        [0.89047878, 0.48063444, 0.2719702 ]],

       [[0.23921591, 0.12623368, 0.03563703],
        [0.11506848, 0.44089497, 0.08147241],
        [0.77622415, 0.25580233, 0.86144409]],

       [[0.72717774, 0.63586846, 0.07958707],
        [0.94974793, 0.46390087, 0.85961402],
        [0.02697514, 0.69354738, 0.60551051]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [52]:
a = np.random.rand(3, 3)
print(a)
print(a.min())
print(a.max())


[[0.16580629 0.85148834 0.23419222]
 [0.24823547 0.04468353 0.195864  ]
 [0.24203154 0.66591293 0.3753899 ]]
0.044683530436747665
0.8514883449917938


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [54]:
a = np.random.random(30)
a.mean()

0.5436777040092171

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [72]:
a = (np.zeros(16)).reshape(4, 4)
np.pad(a, 1, 'constant', constant_values = 1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [73]:
np.pad(a, 1, 'constant', constant_values = 10)

array([[10., 10., 10., 10., 10., 10.],
       [10.,  0.,  0.,  0.,  0., 10.],
       [10.,  0.,  0.,  0.,  0., 10.],
       [10.,  0.,  0.,  0.,  0., 10.],
       [10.,  0.,  0.,  0.,  0., 10.],
       [10., 10., 10., 10., 10., 10.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [75]:
0 * np.nan


nan

In [78]:
np.nan == np.nan

False

In [79]:
np.inf > np.nan

False

In [80]:
np.nan - np.nan

nan

In [86]:
 3*0.1 == 0.3

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [108]:
a = np.diag([1, 2, 3, 4], -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [131]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [193]:
a = np.arange(6*7*8).reshape(6, 7, 8)
dims = a.shape
np.unravel_index(99, dims)

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [153]:
a = [[0,1], [1,0]]
np.tile(a, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [158]:
a = np.random.rand(5, 5)
(a - a.min())/(a.max() - a.min())

array([[0.02014927, 1.        , 0.5097417 , 0.57549973, 0.76391735],
       [0.20417313, 0.88797575, 0.36777727, 0.80117797, 0.75015066],
       [0.        , 0.01338399, 0.27841739, 0.03437719, 0.99774077],
       [0.5327637 , 0.507015  , 0.31103713, 0.54857877, 0.41125291],
       [0.61933213, 0.8499181 , 0.24866144, 0.03614034, 0.07363045]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [171]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
type(color)


numpy.dtype

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [178]:
a = np.arange(15).reshape(5, 3)
b = np.arange(6).reshape(3, 2)
print(a @ b)
np.dot(a, b)


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [202]:
x = np.arange(10)
print(x)
x[(x > 3) & (x <= 8)] *= -1
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [205]:
print(sum(range(5),-1))
type(range(3))

10


range

In [204]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [214]:
Z = np.arange(10)
Z**Z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [219]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [221]:
Z >- Z

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [222]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [223]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [224]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [298]:
np.array(0) / np.array(0)


nan

In [299]:
np.array(0) // np.array(0)

0

In [238]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [272]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))
np.round(Z)

[-5.46594681 -8.29994349  3.40934055  9.07681634  8.01393036 -6.32829624
 -7.15870095 -3.67823178 -5.40836891 -1.35471842]
[-6. -9.  4. 10.  9. -7. -8. -4. -6. -2.]


array([-5., -8.,  3.,  9.,  8., -6., -7., -4., -5., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [295]:
b = np.zeros((2, 2))
a = np.arange(4).reshape(2,2)
np.intersect1d(b,a)

array([0.])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [297]:
np.warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [303]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [322]:
import datetime
current = np.datetime64('today', 'D')
yesterday = current - np.timedelta64(1, 'D')
tomorrow = current + np.timedelta64(1, 'D')
print(yesterday)
print(current)
print(tomorrow)

2018-05-23
2018-05-24
2018-05-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [338]:
dates = np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'), np.timedelta64(1, 'D'))
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [350]:
A = np.zeros((2,2))
B = np.ones((2, 2))
np.add(A,B, out = B)
np.negative(A, out = A)
np.multiply(A, 1/2, out = A)
np.multiply(B, A, out = A)

array([[-0., -0.],
       [-0., -0.]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [366]:
a = np.random.rand(10) * 10 - 5
print(a)
b = np.ceil(a)
print(b)
a.round()
print(np.trunc(a))
print(np.floor(a))
print(a // 1)
print(a.astype(int))

[ 4.89863699 -4.72295927 -2.80091568  3.10681792 -0.40136566  4.58606078
 -3.43178882 -0.87388336  1.58340328 -0.78136636]
[ 5. -4. -2.  4. -0.  5. -3. -0.  2. -0.]
[ 4. -4. -2.  3. -0.  4. -3. -0.  1. -0.]
[ 4. -5. -3.  3. -1.  4. -4. -1.  1. -1.]
[ 4. -5. -3.  3. -1.  4. -4. -1.  1. -1.]
[ 4 -4 -2  3  0  4 -3  0  1  0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [369]:
a = np.tile(arange(5), (5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [384]:
b = np.fromiter((x for x in range(10)), count = 10, dtype = int)
type(x for x in range(10))

generator

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [406]:
a = np.linspace(0, 1, 10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [408]:
np.sort(np.random.rand(10))

array([0.00127901, 0.26481638, 0.27467383, 0.33318067, 0.38475763,
       0.50106987, 0.50576085, 0.74556848, 0.90749481, 0.96867862])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [418]:
a = np.arange(5) + 1
print(np.sum(a))
print(np.multiply.reduce(a))

15
120


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [444]:
A = np.random.rand(2, 2) * 10 // 1
B = np.random.rand(2, 2) * 10 // 1
print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [447]:
a = zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [455]:
Cor = np.random.rand(10, 2) * 10 // 1
print(Cor)
X = Cor[:,0]
Y = Cor[:, 1]
P = np.sqrt(X**2 + Y ** 2)
T = np.arctan2( Y, X)
print(P)
print(T)

[[6. 1.]
 [1. 7.]
 [9. 9.]
 [0. 0.]
 [7. 3.]
 [6. 3.]
 [1. 2.]
 [1. 9.]
 [1. 0.]
 [5. 2.]]
[ 6.08276253  7.07106781 12.72792206  0.          7.61577311  6.70820393
  2.23606798  9.05538514  1.          5.38516481]
[0.16514868 1.42889927 0.78539816 0.         0.40489179 0.46364761
 1.10714872 1.46013911 0.         0.38050638]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [463]:
a = np.random.rand(10) * 10 //1
print(a)
a[np.argmax(a)] = 0
a

[2. 8. 2. 6. 1. 9. 6. 7. 3. 9.]


array([2., 8., 2., 6., 1., 0., 6., 7., 3., 9.])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [466]:
a = np.random.random((4, 4))
a

array([[0.10942032, 0.12719686, 0.88578248, 0.52346584],
       [0.81285765, 0.35799083, 0.43701708, 0.48371957],
       [0.12748404, 0.98302033, 0.40956187, 0.64867143],
       [0.9334411 , 0.79105072, 0.20861707, 0.82287231]])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)